class CreateBooks < ActiveRecord::Migration
  # this is generated by rails generate migration command.  Change only specifies add because delete can be guessed.
  #def change
  #  create_table :books do |t|
  #  end
  #end
  
  #string may be translated to varchar2(255), text is much longer.  String vs text also depends on the database: MySQL is different from Postgres
  def up
    create_table :books do |t|
      t.string   :title
      t.text     :title_chinese
      t.string   :author_string
      t.string   :edition
      t.datetime :published_date
      t.string   :published_city
      t.string   :publisher_name
      # Add fields that let Rails automatically keep track
      # of when books are added or modified:
      t.timestamps
    end
  end

  def down
    drop_table :books
  end
  
end
